# Generated by Django 2.0.4 on 2018-04-12 21:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbr', models.CharField(max_length=5)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Forecasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam', models.ForeignKey(on_delete=False, to='reporter.Dam')),
            ],
            options={
                'verbose_name_plural': 'Forecasts',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('reference_name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.AddField(
            model_name='forecasts',
            name='species',
            field=models.ForeignKey(on_delete=False, to='reporter.Species'),
        ),
    ]
